### ISSUE TITLE
Firmware retract Panel

### ISSUE THREAD

**Issue by MSergW** [jordanruthe/KlipperScreen#101]
hi!
tell me, please, how to add firmware retract setting to the print control menu?
https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md#firmware-retraction

on printer lcd its like:
```
[menu __main FWRT]
type: list
name: FW retract

[menu __main FWRT retract_length]
type: input
name: Length= {'%02.2f' % menu.input}
input: {printer.firmware_retraction.retract_length}
input_min: 0.0
input_max: 10
input_step: 0.05
realtime: True
gcode:
    SET_RETRACTION RETRACT_LENGTH={'%.3f' % menu.input}

[menu __main FWRT retract_speed]
type: input
name: Speed= {'%2.0f' % menu.input}
input: {printer.firmware_retraction.retract_speed}
input_step: 1
input_min: 1
input_max: 100
input_step: 1.
realtime: True
gcode:
    SET_RETRACTION RETRACT_SPEED={'%.3f' % menu.input}

[menu __main FWRT unretract_extra_length]
type: input
name: UR ExLen={'%01.3f' % menu.input}
input: {printer.firmware_retraction.unretract_extra_length}
input_min: 0.0
input_max: 0.1
input_step: 0.001
realtime: True
gcode:
    SET_RETRACTION UNRETRACT_EXTRA_LENGTH={'%.4f' % menu.input}
```

**Comment by tonywright** [comment]
I would like to second this, it would be really useful to have firmware retraction available on the printer control panel. I have had a look at adding a panel and got as far as creating the UI but the values for the retraction are coming from the config file instead of the actual "Live" values as changed elsewhere. IE in printer.cfg I have firmware retraction length set to 0.5, if I adjust this to 0.75 in mainsail front-end  KlipperScreen still shows the 0.5 value not the adjusted value of 0.75 (Which doesn't get stored in config) This is different to acceleration which does work correctly.

**Comment by alfrix** [comment]
> I would like to second this, it would be really useful to have firmware retraction available on the printer control panel. I have had a look at adding a panel and got as far as creating the UI but the values for the retraction are coming from the config file instead of the actual "Live" values as changed elsewhere. IE in printer.cfg I have firmware retraction length set to 0.5, if I adjust this to 0.75 in mainsail front-end KlipperScreen still shows the 0.5 value not the adjusted value of 0.75 (Which doesn't get stored in config) This is different to acceleration which does work correctly.

it's hard to say without looking or trying the code, you may just be missing the process_update in the panel to grab moonraker responses, you can take a look at how other panels do this

**Comment by alfrix** [comment]
and to the OP, in you can sort of do this in KS but you need some advanced macros to go along with it, and it will be far worse than doing a dedicated panel
```
[menu __main config FWRT]
name: Firmware Retract
icon: retract

[menu __main FWRT config retract_length+]
name: Length +
icon: retract
gcode:
    MACRO_that_adds_more_retraction

[menu __main config FWRT retract_length-]
name: Length -
icon: retract
gcode:
    MACRO_that_substract_retraction

[menu __main config FWRT speed+]
name: Speed +
icon: speed+
gcode:
    MACRO_that_adds_more_speed

[menu __main config FWRT speed-]
name: Speed -
icon: speed-
gcode:
    MACRO_that_slows_retraction
```

**Comment by tonywright** [comment]
alfrix, you were right (sort of) I had to add "firmware_retraction" to two places in "screen.py". my fwretraction.py panel is now working well.  How do I go about asking to add the two lines to screen.py? Otherwise it will stop working every time there is an update. I am happy to give you the panel file if you want to add it to the project for others including the OP

**Comment by alfrix** [comment]
you can do a PR with the panel if you want

or attach it here, whatever you like

**Comment by tonywright** [comment]
Although the panel works ok I can only make it available in KlipperScreen when the printer isn't printing. Is there a way to add it to the settings screen that is shown while printing?  It also requires the modification to screen.py to add the firmware retraction settings. I have attached it here (remove the .txt extension)
[fwretraction.py.txt](https://github.com/jordanruthe/KlipperScreen/files/8463688/fwretraction.py.txt)

**Comment by alfrix** [comment]
i see that you copied from the limits panel, i had to do a lot of extra work, but i have it working now

**Comment by alfrix** [comment]
and thank you tony i appreciate the help
