### ISSUE TITLE
Changing the font size

### ISSUE THREAD

**Issue by Shadow2091** [jordanruthe/KlipperScreen#133]
Hey! Could you add the option to select the font size in the settings, since the standard font on a 4" screen seems very small to me, although the tiles and button icons are of a good size. Thank you!

**Comment by jordanruthe** [comment]
Unfortunately, changing the font size to be bigger currently has some cascading problems with making items appear off the screen. 

I do want to fix those problems at some point to make the font bigger.

**Comment by alfrix** [comment]
i did experiment with this some label cutting needs to happen because using Pango word wrap adds extra blank space at he bottom and it's problematic in some panels

This is [Big icons and text ](https://github.com/alfrix/KlipperScreen/commit/93398dcaf497835f021af70dce6a568172d87328)using the #144 as base:
![extrude](https://user-images.githubusercontent.com/1247237/116997453-339d4380-acb3-11eb-881d-b4b5aac8282e.png)
![fan](https://user-images.githubusercontent.com/1247237/116997458-3435da00-acb3-11eb-9a77-5c4614c07fd0.png)
![move](https://user-images.githubusercontent.com/1247237/116997459-34ce7080-acb3-11eb-8ea7-b9aaac55c61a.png)
![options](https://user-images.githubusercontent.com/1247237/116997460-34ce7080-acb3-11eb-9cce-0e530cc0f71b.png)
![printing](https://user-images.githubusercontent.com/1247237/116997464-35670700-acb3-11eb-824d-6c238a592469.png)
![system](https://user-images.githubusercontent.com/1247237/116997466-35670700-acb3-11eb-8690-030b8319e136.png)
![tune](https://user-images.githubusercontent.com/1247237/116997467-35ff9d80-acb3-11eb-9d29-19741570fe5d.png)

also made a font selector test
https://github.com/alfrix/KlipperScreen/commit/28d9ab7e3e775e81418673af6c8e3d34b7c78a55

**Comment by SaulGoodman1337** [comment]
> 
> 
> i did experiment with this some label cutting needs to happen because using Pango word wrap adds extra blank space at he bottom and it's problematic in some panels
> 
> This is [Big icons and text ](https://github.com/alfrix/KlipperScreen/commit/93398dcaf497835f021af70dce6a568172d87328)using the #144 as base:
> ![extrude](https://user-images.githubusercontent.com/1247237/116997453-339d4380-acb3-11eb-881d-b4b5aac8282e.png)
> ![fan](https://user-images.githubusercontent.com/1247237/116997458-3435da00-acb3-11eb-9a77-5c4614c07fd0.png)
> ![move](https://user-images.githubusercontent.com/1247237/116997459-34ce7080-acb3-11eb-8ea7-b9aaac55c61a.png)
> ![options](https://user-images.githubusercontent.com/1247237/116997460-34ce7080-acb3-11eb-9cce-0e530cc0f71b.png)
> ![printing](https://user-images.githubusercontent.com/1247237/116997464-35670700-acb3-11eb-824d-6c238a592469.png)
> ![system](https://user-images.githubusercontent.com/1247237/116997466-35670700-acb3-11eb-8690-030b8319e136.png)
> ![tune](https://user-images.githubusercontent.com/1247237/116997467-35ff9d80-acb3-11eb-9d29-19741570fe5d.png)
> 
> also made a font selector test
> [alfrix@28d9ab7](https://github.com/alfrix/KlipperScreen/commit/28d9ab7e3e775e81418673af6c8e3d34b7c78a55)

Hi,
thanks for this! but how can i use this?
i have a very cheap and simple 3.5 TFT and the fontsize here is very tiny.... 
i need a quickfix before i switch to a hyperpixel or something like that

**Comment by alfrix** [comment]
Navigate the files on your pi and find
_/home/pi/KlipperScreen/ks_includes/KlippyGtk.py_
change
`font_ratio = [51, 30]`
to
`font_ratio = [43, 29]`

this will make the font 11px instead of 9px, (you can  do the other changes in #169)
currently it's the maximum you can have without issues
