### ISSUE TITLE
KlipperScreen is in an undefined state after switching the printer off and on again.

### ISSUE THREAD

**Issue by JWRu** [jordanruthe/KlipperScreen#967]
My printer is configured (via idle_timeout) to switch off by a smart plug after it is idle for some time. 
Then, of course, Klipper is no longer accessible. 
When I switch the printer on again (via Mainsail or KlipperScreen), KlipperScreen seems to be in an undefined state - e.g. actual temperatures are not shown. 
I have to restart KlipperScreen to get it working again.

**Comment by DomiStyle** [comment]
I think I'm running into the same issue but an emergency stop from the web interface is enough to trigger this. KlipperScreen will still send commands to the printer (e.g. I can still move the axes) but it will not update any information anymore (current print, temperatures, etc.). A restart also solves this for me.

Here's the log file: https://gist.github.com/DomiStyle/d026c4f85fa45a1314f867aeb07e51cb

This is a print start followed by an emergency stop, followed by a restart of KlipperScreen because it didn't update anymore.
